### ISSUE TITLE
Unable to verify

### ISSUE THREAD

**Issue by J-Chapman** [jangrewe/hexbright#1]
I've tried to copy and paste the code to Arduio both 1.0.5 & 1.0.3, but it came up with multiple errors.  I don't know if I'm doing something wrong or what.

Here are the errors I get when I try to verify
http://s14.postimg.org/rxtf74ucx/Screenshot_from_2013_07_19_12_23_37.png

**Comment by jangrewe** [comment]
Hi, that looks like you haven't installed Daniel Hilton's library yet, please prepare your Arduino IDE like this: https://github.com/dhiltonp/hexbright

**Comment by J-Chapman** [comment]
Thanks that was pretty slow of me to miss that obvious step.
